---
- name : install Docker on ubuntu server
  hosts : devops-server
  become : true

  tasks : 
    - name : update apt cache
      apt :
        update_cache : yes

    - name : Install Docker Dependencies
      apt :
        name: 
          - docker.io
          - python3-pip
        state : present

    - name : Install Docker Compose
      pip :
        name: docker-compose
        executable : pip3
        state : present
    
     - name: Start and enable Docker service
       service:
        name: docker
        state: started
        enabled: yes

     - name: Ensure Docker daemon is started
       command: docker info
       register: docker_status
       retries: 5
       delay: 7
       until: docker_status.rc == 0

    # - name: Copy Docker Compose file to the server
    #   copy:
    #     src: ../docker-compose.yml
    #     dest: /home/ubuntu/docker-compose.yml
    #     mode: '0755'

    # - name: Start Docker containers using Docker Compose
    #   command: docker-compose up -d
    #   args:
    #     chdir: /home/ubuntu


    