on:
  push:
    branches: [ "dev" ]
    
jobs:
  Terraform:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.SECRET_KEY }}
        aws-region: us-east-1 
        
    - name: Set up SSH
      run: |
        mkdir -p ~/Downloads
        echo "${{ secrets.EC2_KEY_PAIR }}" > ~/Downloads/my-second-new-key.pem
        chmod 600 ~/Downloads/my-second-new-key.pem

    - name: Add SSH key to the agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_KEY_PAIR }}
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.9.1
        
    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      if: github.ref == 'refs/heads/dev'
      run: terraform apply -auto-approve

    - name: Create PEM file from secret
      run: |
        echo "${{ secrets.EC2_KEY_PAIR }}" > ./.github/workflows/my-second-new-key.pem
        chmod 600 ./.github/workflows/my-second-new-key.pem
      
    - name: Run Ansible playbook with Inventory
      run: |
        ls
        ansible-playbook --private-key ./.github/workflows/my-second-new-key.pem -i ./.github/workflows/inventory.ini playbook.yml
      # env:
      #   EC2_KEY_PAIR: ./.github/workflows/my-second-new-key.pem
      #   ANSIBLE_HOST_KEY_CHECKING: False
      
    
